# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "48a0f5e2ec6e42fae077af3ea19bb608"
application_url = "https://considering-switched-just-anderson.trycloudflare.com"
embedded = true
name = "user-created-tag"
handle = "user-created-tag"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,write_orders, write_draft_orders, write_discounts, write_content,read_content, read_products, read_customers, read_orders, read_draft_orders, read_discounts,read_product_listings,write_product_listings"

[auth]
redirect_urls = [
  "https://considering-switched-just-anderson.trycloudflare.com/auth/callback",
  "https://considering-switched-just-anderson.trycloudflare.com/auth/shopify/callback",
  "https://considering-switched-just-anderson.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "product-tag-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
